### ISSUE TITLE
Build fails on latest Zig

### ISSUE THREAD

**Issue by notramo** [Luukdegram/apple_pie#86]
@Luukdegram, the build fails on latest Zig.
`zig build example router` fails because the `build.zig` format has been changed.
When including `apple_pie` from another project, the following error is thrown:
```
.zigmod/deps/git/github.com/Luukdegram/apple_pie/src/router.zig:199:72: error: function with comptime-only return type 'router.Route(*main.Context)' requires all parameters to be comptime
        pub fn get(path: []const u8, comptime handlerFn: anytype) Route(Context) {
                                                                  ~~~~~^~~~~~~~~
.zigmod/deps/git/github.com/Luukdegram/apple_pie/src/router.zig:23:18: note: struct requires comptime because of this field
        handler: Handler,
                 ^~~~~~~
.zigmod/deps/git/github.com/Luukdegram/apple_pie/src/router.zig:23:18: note: use '*const fn(*main.Context, *response.Response, Request, []const trie.Entry) anyerror!void' for a function pointer type
        handler: Handler,
                 ^~~~~~~
.zigmod/deps/git/github.com/Luukdegram/apple_pie/src/router.zig:199:20: note: param 'path' is required to be comptime
        pub fn get(path: []const u8, comptime handlerFn: anytype) Route(Context) {
                   ^~~~
```

**Comment by Luukdegram** [comment]
Due to the reliance on `async`, I only support using the old stage1 compiler currently. This means you cannot use the latest version of the Zig compiler until async is implemented (planned for 0.11 release 16th of May), you will have to use `0.10.x`. I have no plans on removing the dependency on the async feature due to my limited time. Once async is implemented, I will update and work on this project again. See the included build.zig file in this repo for an example on how to use the stage1 compiler.
